services:
  # ─── Your Go Application ─────────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temple_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_NAME: temple_db
      DB_USER: temple_user
      DB_PASSWORD: nature123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GOOGLE_APPLICATION_CREDENTIALS: app/serviceAccountKey.json
      FIREBASE_PROJECT_ID: tms-app-38fc7
      FCM_CREDENTIALS_PATH: app/serviceAccountKey.json
      FCM_PROJECT_ID: tms-app-38fc7
      
       TURNSTILE_SECRET_KEY=0x4AAAAAACOHzJSWYw-ecMHTktspGlo05ag
        VITE_ENABLE_TURNSTILE=true
    volumes:
      - ./uploads:/data/uploads
      - ./files:/data/files
      - ./logs:/data/logs
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
     
    networks:
      - temple_network
    restart: unless-stopped
  
  # ─── Postgres Database ───────────────────────────────────────────────────────
  postgres:
    image: postgres:15
    container_name: temple_postgres
    environment:
      POSTGRES_DB: temple_db
      POSTGRES_USER: temple_user
      POSTGRES_PASSWORD: nature123
    ports:
      - "5433:5433"
    command: postgres -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - temple_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # ─── Redis Cache ─────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: temple_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - temple_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
  
  # ─── Kafka Broker ───────────────────────────────────────────────────────────

volumes:
  postgres_data:
  redis_data:
  #kafka_data:
  #kafka_meta:

networks:
  temple_network:
    driver: bridge
